baseURL = "https://docs.makedeb.org/"
languageCode = "en-us"
title = "makedeb Docs"
theme = "makedeb"
pluralizelisttitles = "false"

[params]
site_desc = "A simplicity-focused packaging tool for Debian archives"
hw_url = "hunterwittenborn.com"
makedeb_url = "makedeb.org"
github_url = "github.com"
